'''
A tea stall has a digital token display.

For every customer in line, a token number is printed and chai is served.

Task:

Use a 'for' loop to generate token numbers form 1 to 10 using range().

Print : 'Serving chai to token #[number]'

'''

# Loop through token numbers from 1 to 10
for token in range(1, 11):

    # Print a message indicating that chai is being served to the current token
    print(f'Serving chai to Token#{token}')


'''

Explanation
range(1, 11) generates the numbers 1 through 10.
The starting value (1) is included.
The ending value (11) is excluded.
for token in range(1, 11):
Iterates over each number generated by range().
During each iteration, the variable token stores the current number.
print(f'Serving chai to Token#{token}')
Uses an f-string to insert the current value of token into the message.
#{token} prints the token number (e.g., #1, #2, etc.).
Output
Serving chai to Token#1
Serving chai to Token#2
Serving chai to Token#3
Serving chai to Token#4
Serving chai to Token#5
Serving chai to Token#6
Serving chai to Token#7
Serving chai to Token#8
Serving chai to Token#9
Serving chai to Token#10

This is a simple example of a for loop, which repeats a block of code a fixed number of times.

'''